### ISSUE TITLE
Bug - Performance mode under Windows 

### ISSUE THREAD

**Issue by cavo789** [faceair/atom-goto-definition#51]
Under Windows, the performance mode doesn't work, see screen capture below.
The first screen is with the normal mode : we can see the different files and the location are correctly spelled.

In the second screen, the location `C:\FolderName\..`. is incorrectly set to `C, line NaN`, the file can't then be opened.

![normal mode](https://cloud.githubusercontent.com/assets/355999/24747729/96a96a12-1abd-11e7-8853-a4936c12fc9f.png)

![performance mode](https://cloud.githubusercontent.com/assets/355999/24747747/a342e8b6-1abd-11e7-85d1-c87504762b4d.png)

PS : would be nice to better explain how to install ripgrep because not directly intuitive.

thanks !

**Comment by alexandrosdelta** [comment]
This is because the path, line, column and code are split wherever a colon is found, 
e.g. /usr/h:334:23: string
It's rg that currently has this semicolon hardcoded, so this plugin has to split at that character. 
But it's a problem for Windows because the absolute path will be something like C:\Windows\afile.txt 
I made a different version of searcher.js to cater for that, and will make a pull request.

**Comment by faceair** [comment]
Thanks @alexandrosdelta #53
This bug fixed in v1.3.2.
